[[news]]
date = "2026.01"
content = "One paper accepted to ICASSP 2026."

[[news]]
date = "2025.05"
content = "One paper accepted to Interspeech 2025."

[[news]]
date = "2025.05"
content = "One paper accepted to ACL 2025."

[[news]]
date = "2025.04"
content = "Presented virtually at ICASSP 2025."

[[news]]
date = "2024.12"
content = "Three papers accepted to ICASSP 2025."

[[news]]
date = "2024.08"
content = "One paper accepted to ISCSLP 2024."

[[news]]
date = "2024.06"
content = "Achieved 1st and 4th place in Task 1 and Task 4 of the DCASE 2024 Challenge."

[[news]]
date = "2024.04"
content = "Presented one poster at ICASSP 2024 in Seoul, Korea."

[[news]]
date = "2024.03"
content = "Achieved 2nd and 3rd place in the ICME 2024 ASC Grand Challenge."

[[news]]
date = "2023.12"
content = "Two papers accepted to ICASSP 2024."

