type = "card"
title = "Services"
description = "Professional services and community involvement."

[[items]]
title = "Reviewer"
subtitle = "ICASSP"
date = "2026"

[[items]]
title = "Reviewer"
subtitle = "Interspeech"
date = "2026"

[[items]]
title = "Reviewer"
subtitle = "SLT"
date = "2026"

[[items]]
title = "Reviewer"
subtitle = "NeurIPS"
date = "2026"

[[items]]
title = "Reviewer"
subtitle = "ICLR"
date = "2026/2025"

[[items]]
title = "Reviewer"
subtitle = "IJCNN"
date = "2025"

[[items]]
title = "Reviewer"
subtitle = "Speech Communication"
date = "2025"
